version: '3.7'
services:
  mysql:
    container_name: base_mysql
    image: quay.io/fedora/mysql-80:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: banco_db
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - red_interna
  
  cliente-persona-devsu:
    container_name: cliente-persona-devsu
    image: cliente-persona-devsu:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://base_mysql:3306/banco_db 
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    networks:
      - red_interna
    depends_on:
      - mysql
      - rabbitmq

  cuenta-movimiento-service-devsu:
    container_name: cuenta-movimiento-service-devsu
    image: cuenta-movimiento-service:latest
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: jdbc:mysql://base_mysql:3306/banco_db 
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    networks:
      - red_interna
    depends_on:
      - mysql
      - rabbitmq
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - red_interna
    restart: always

volumes:
  mysql_data:

networks:
  red_interna:
    name: red_interna
    driver: bridge
